plugins {
    id 'java'
    id 'java-library'
    id 'maven-publish'
    id "io.freefair.lombok" version "9.5.0"
    id 'io.spring.dependency-management' version '1.1.7'
}

group 'tech.aomi.common'
version '1.0.4_21-SNAPSHOT'

apply from: 'https://onegit.com/enterprise/public/raw/master/spring-libraries.gradle'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(26)
    }
}

repositories {
    mavenCentral()
    maven {
        url "https://nexus.stelarx.tech/repository/maven-snapshots/"
    }
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.boot:spring-boot-dependencies:4.1.1"
    }
}

dependencies {
    implementation spring_boot.data_mongodb
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            versionMapping {
                allVariants {
                    fromResolutionResult()
                }
            }
        }
    }
    repositories {
        maven {
            url = project.version.endsWith('-SNAPSHOT')
                    ? 'https://nexus.stelarx.tech/repository/maven-snapshots/'
                    : 'https://nexus.stelarx.tech/repository/maven-releases/'
            credentials {
                username System.getenv('REPO_USERNAME')
                password System.getenv('REPO_PASSWORD')
            }
        }
    }
}
